version: "3"
services:

  java:
    build:
      context: ./
    tty: true
    ports:
      - "8080:8080"
    container_name: spring
    depends_on:
      - mongo
    networks:
      - shared-net

  mongo:
    image: 'mongo'
    tty: true
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge
